# Generated by Django 4.2.6 on 2023-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='company',
            name='companyName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='taxNumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='operationtype',
            name='operationType',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
