# Generated by Django 4.2.6 on 2023-10-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_adress_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
